"""Retarget the 27-DOF anatomical hand onto a robot hand, and check it in MuJoCo.

Why
---
Everything measured in this project so far is a property of *human* hand motion:
the prior generates 27 anatomical DOF, and the claims about modularity and
composition are claims about that representation. Nothing yet shows the motion
is usable by a robot, which is the question a robotics venue actually asks.

This is the smallest thing that answers it honestly. It does not need RL, a
task, or a policy. It asks:

1. Does human motion generated by the prior fit inside a robot hand's joint
   limits, and how much is lost when it does not?
2. Does it self-collide when replayed on the robot?
3. **Do compositions the prior was never trained on transfer as well as the ones
   it saw?** That is the claim worth making -- the library is only useful if
   novel sequences survive the trip to hardware kinematics.

The mapping
-----------
Shadow Hand's joint naming is anatomical, so the correspondence is by role --
but this project's rule is to infer and check, not to assume, and there is a
check available: the two models' joint *ranges* were designed independently, so
agreement between them is evidence the roles line up.

    index_mcp_abd  [-20, 20]   FFJ4 [-20, 20]    identical
    thumb_mcp_abd  [-10, 10]   THJ3 [-12, 12]    within 2 degrees
    thumb_ip_flex  [-15, 80]   THJ1 [-15, 90]    lower bound identical
    index_mcp_flex [-20, 90]   FFJ3 [-15, 90]    upper bound identical

The thumb's proximal joints agree less well (``thumb_mcp_flex`` [-10, 55]
against THJ2 [-40, 40]), and that is reported rather than hidden: the clip
fraction per joint is part of the output, because a joint that saturates on
the robot is the same failure mode as the dead DOF the retargeting audit found
in three public datasets.

Two joints have no anatomical counterpart here and stay at zero: ``rh_LFJ5``,
the little-finger metacarpal that gives the palm its arch, and the two wrist
joints -- MANO has no forearm, so wrist rotation was never recoverable.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from caredex.hand_model import DOF_INDEX, LIMITS_HI, LIMITS_LO

#: Anatomical DOF -> Shadow Hand joint. Roles first, corroborated by the range
#: agreement documented above.
SHADOW_MAP: dict[str, str] = {
    "index_mcp_abd": "rh_FFJ4", "index_mcp_flex": "rh_FFJ3",
    "index_pip_flex": "rh_FFJ2", "index_dip_flex": "rh_FFJ1",
    "middle_mcp_abd": "rh_MFJ4", "middle_mcp_flex": "rh_MFJ3",
    "middle_pip_flex": "rh_MFJ2", "middle_dip_flex": "rh_MFJ1",
    "ring_mcp_abd": "rh_RFJ4", "ring_mcp_flex": "rh_RFJ3",
    "ring_pip_flex": "rh_RFJ2", "ring_dip_flex": "rh_RFJ1",
    "pinky_mcp_abd": "rh_LFJ4", "pinky_mcp_flex": "rh_LFJ3",
    "pinky_pip_flex": "rh_LFJ2", "pinky_dip_flex": "rh_LFJ1",
    "thumb_cmc_abd": "rh_THJ5", "thumb_cmc_flex": "rh_THJ4",
    "thumb_mcp_abd": "rh_THJ3", "thumb_mcp_flex": "rh_THJ2",
    "thumb_ip_flex": "rh_THJ1",
}

#: Robot joints with no counterpart in the 27-DOF model, held at zero.
#: ``rh_LFJ5`` is the little-finger metacarpal (palm arch); the wrist joints are
#: unrecoverable from MANO, which has no forearm.
SHADOW_UNMAPPED = ("rh_LFJ5", "rh_WRJ1", "rh_WRJ2")

DEFAULT_SHADOW_XML = r"D:\datasets\mujoco_menagerie\shadow_hand\right_hand.xml"


@dataclass
class RetargetReport:
    """What the trip to the robot cost, per joint and overall."""

    n_frames: int
    clip_fraction: float
    per_joint_clip: dict[str, float] = field(default_factory=dict)
    #: Frames where any two geometries touch at all. Not a defect: fingers rest
    #: against each other in a closed grasp.
    touching_frames: float = 0.0
    #: Frames where the overlap exceeds the tolerance. This is the defect rate.
    penetrating_frames: float = 0.0
    max_penetration_mm: float = 0.0
    mean_penetration_mm: float = 0.0

    def describe(self) -> str:
        worst = sorted(self.per_joint_clip.items(), key=lambda kv: -kv[1])[:4]
        lines = [
            f"{self.n_frames:,} frames  clipped {self.clip_fraction:.2%}  "
            f"touching {self.touching_frames:.1%}  "
            f"penetrating {self.penetrating_frames:.1%}  "
            f"max depth {self.max_penetration_mm:.1f} mm",
            "  worst joints: " + ", ".join(f"{n} {v:.1%}" for n, v in worst),
        ]
        return "\n".join(lines)


class ShadowHand:
    """Kinematic replay of anatomical hand motion on the Shadow Hand.

    Kinematic, not dynamic: ``mj_forward`` places the model at each pose and the
    contact list is read off. That is enough to answer "would this motion be
    geometrically valid on the robot" and deliberately stops short of claiming
    anything about forces, which no part of this project measures.
    """

    def __init__(self, xml: str | Path = DEFAULT_SHADOW_XML):
        import mujoco

        self._mj = mujoco
        path = Path(xml)
        if not path.exists():
            raise FileNotFoundError(
                f"{path} not found. Fetch the hand model with:\n"
                "  git clone --depth 1 --filter=blob:none --sparse "
                "https://github.com/google-deepmind/mujoco_menagerie.git\n"
                "  cd mujoco_menagerie && git sparse-checkout set shadow_hand"
            )
        self.model = mujoco.MjModel.from_xml_path(str(path))
        self.data = mujoco.MjData(self.model)

        self.joint_qpos: dict[str, int] = {}
        self.joint_range: dict[str, tuple[float, float]] = {}
        for i in range(self.model.njnt):
            name = mujoco.mj_id2name(self.model, mujoco.mjtObj.mjOBJ_JOINT, i)
            if name is None:
                continue
            self.joint_qpos[name] = int(self.model.jnt_qposadr[i])
            lo, hi = self.model.jnt_range[i]
            self.joint_range[name] = (float(lo), float(hi))

        missing = set(SHADOW_MAP.values()) - set(self.joint_qpos)
        if missing:
            raise KeyError(f"model lacks mapped joints: {sorted(missing)}")

    def retarget(self, q_deg: np.ndarray) -> tuple[np.ndarray, dict[str, float]]:
        """``(T, 27)`` anatomical degrees -> ``(T, nq)`` robot qpos, plus clip rates.

        Angles transfer directly rather than being rescaled between the two
        limit boxes. Rescaling would hide exactly what this is meant to measure:
        a joint the robot cannot reach should show up as saturation, not be
        silently squeezed into range.
        """
        q_deg = np.asarray(q_deg, dtype=np.float64)
        qpos = np.zeros((len(q_deg), self.model.nq))
        clip: dict[str, float] = {}
        for dof, joint in SHADOW_MAP.items():
            lo, hi = self.joint_range[joint]
            v = np.radians(q_deg[:, DOF_INDEX[dof]])
            clip[joint] = float(np.mean((v < lo) | (v > hi)))
            qpos[:, self.joint_qpos[joint]] = np.clip(v, lo, hi)
        return qpos, clip

    def replay(self, q_deg: np.ndarray, penetration_tol_mm: float = 0.5) -> RetargetReport:
        """Replay and report contact, separating touching from penetrating.

        MuJoCo's contact count is not a collision count: fingers resting against
        each other in a closed grasp register contacts and are perfectly valid
        hand poses. Counting ``ncon > 0`` as self-collision gave 32% on
        OakInk-Image against the 5.5% this repo's own mesh test reports.

        What matters is **depth**: ``contact.dist`` is negative when geometries
        overlap, and a pose is only invalid when that overlap exceeds the
        solver's own contact margin. The tolerance is in millimetres because
        that is the scale a hand is judged at.
        """
        qpos, clip = self.retarget(q_deg)
        tol = penetration_tol_mm / 1000.0
        touching = penetrating = 0
        depths: list[float] = []
        for frame in qpos:
            self.data.qpos[:] = frame
            self._mj.mj_forward(self.model, self.data)
            n = int(self.data.ncon)
            if n == 0:
                continue
            touching += 1
            worst = min(float(self.data.contact[i].dist) for i in range(n))
            if worst < -tol:
                penetrating += 1
                depths.append(-worst)
        n_frames = len(qpos)
        return RetargetReport(
            n_frames=n_frames,
            clip_fraction=float(np.mean(list(clip.values()))),
            per_joint_clip=clip,
            touching_frames=touching / max(n_frames, 1),
            penetrating_frames=penetrating / max(n_frames, 1),
            max_penetration_mm=1000.0 * max(depths, default=0.0),
            mean_penetration_mm=1000.0 * float(np.mean(depths)) if depths else 0.0,
        )


def anatomical_limits_vs(robot: ShadowHand) -> str:
    """Side-by-side limit table, the evidence that the role mapping is right."""
    rows = ["  anatomical DOF        our limits        robot joint     robot limits"]
    for dof, joint in SHADOW_MAP.items():
        lo, hi = np.degrees(robot.joint_range[joint])
        i = DOF_INDEX[dof]
        rows.append(
            f"  {dof:<20} [{LIMITS_LO[i]:>6.0f},{LIMITS_HI[i]:>6.0f}]   "
            f"{joint:<12} [{lo:>6.0f},{hi:>6.0f}]"
        )
    return "\n".join(rows)


#: Abduction joints, the only DOF the correction below is allowed to touch.
#: Flexion carries what the motion *is*; abduction carries how far apart the
#: fingers are held, which is exactly the quantity a thicker robot finger needs
#: more of. Correcting flexion instead would change the gesture.
SHADOW_ABDUCTION = ("rh_FFJ4", "rh_MFJ4", "rh_RFJ4", "rh_LFJ4", "rh_THJ3")


class PenetrationResolver:
    """Spread the fingers just enough to stop the robot hand overlapping itself.

    Direct joint-angle transfer puts adjacent Shadow Hand fingers inside each
    other in a quarter to three quarters of frames, and the overlap is not
    diffuse: on OakInk-Image, 2099 of 5773 penetrating contacts are index-distal
    against middle-distal, and the top six body pairs are all index-against-
    middle. Human index and middle fingers lie adjacent comfortably; the robot's
    are thicker, so the same angles collide.

    The correction is coordinate descent on the abduction joints only. At each
    step every abduction joint is tried at plus and minus one increment and the
    move that most reduces the deepest penetration is kept, stopping as soon as
    the pose is clear. Which sign spreads which finger is **not** assumed --
    Shadow's abduction axes point ``[0,-1,0]`` for the index and middle fingers
    and ``[0,1,0]`` for the ring and little, so a hand-written "spread" rule
    would be right for half the hand and wrong for the other half. Trying both
    and keeping what measurably helps needs no such convention.

    Deliberately limited: it never touches flexion, and it reports the angular
    cost it incurred, because a correction that resolves every collision by
    destroying the gesture has not solved anything.
    """

    def __init__(self, hand: "ShadowHand", tol_mm: float = 0.5,
                 step_deg: float = 1.5, max_deg: float = 18.0, max_iters: int = 12):
        self.hand = hand
        self.tol = tol_mm / 1000.0
        self.step = np.radians(step_deg)
        self.max_delta = np.radians(max_deg)
        self.max_iters = max_iters
        self.adr = [hand.joint_qpos[j] for j in SHADOW_ABDUCTION if j in hand.joint_qpos]
        self.limits = [hand.joint_range[j] for j in SHADOW_ABDUCTION if j in hand.joint_qpos]

    def _depth(self, frame: np.ndarray) -> float:
        d, m = self.hand.data, self.hand.model
        d.qpos[:] = frame
        self.hand._mj.mj_forward(m, d)
        n = int(d.ncon)
        if n == 0:
            return 0.0
        return max(0.0, -min(float(d.contact[i].dist) for i in range(n)))

    def resolve(self, frame: np.ndarray, origin: np.ndarray) -> tuple[np.ndarray, float]:
        """Return a corrected frame and the depth still remaining."""
        cur = frame.copy()
        depth = self._depth(cur)
        for _ in range(self.max_iters):
            if depth <= self.tol:
                break
            best = (depth, None)
            for k, (adr, (lo, hi)) in enumerate(zip(self.adr, self.limits)):
                for sign in (1.0, -1.0):
                    v = cur[adr] + sign * self.step
                    if not (lo <= v <= hi) or abs(v - origin[adr]) > self.max_delta:
                        continue
                    trial = cur.copy()
                    trial[adr] = v
                    d = self._depth(trial)
                    if d < best[0] - 1e-9:
                        best = (d, trial)
            if best[1] is None:
                break
            depth, cur = best
        return cur, depth

    def resolve_trajectory(self, q_deg: np.ndarray) -> tuple[np.ndarray, dict]:
        qpos, clip = self.hand.retarget(q_deg)
        out = np.empty_like(qpos)
        before = after = 0
        deltas: list[float] = []
        for i, frame in enumerate(qpos):
            d0 = self._depth(frame)
            before += d0 > self.tol
            fixed, d1 = self.resolve(frame, frame)
            after += d1 > self.tol
            deltas.append(float(np.degrees(np.abs(fixed[self.adr] - frame[self.adr]).sum())))
            out[i] = fixed
        n = max(len(qpos), 1)
        return out, {
            "n_frames": len(qpos),
            "penetrating_before": before / n,
            "penetrating_after": after / n,
            "resolved_fraction": (before - after) / max(before, 1),
            "mean_abduction_change_deg": float(np.mean(deltas)),
            "max_abduction_change_deg": float(np.max(deltas)) if deltas else 0.0,
            "clip_fraction": float(np.mean(list(clip.values()))),
        }
