"""Emit Table II rows in the manuscript's own format for the new and re-run sweeps.

Columns, as in the paper: dataset and axis, eta^2 of each factor, interaction excess with z, difficulty, % naive,
p against zero, p against the zero-truth control (Welch), n. Screen values come from the stored screen JSONs,
difficulty from results.json at budget 256 on the perframe prior. Incomplete sweeps are printed with their seed
count and marked, so a partial row is never mistaken for a finished one.

This only formats numbers other scripts computed; readings live in the runs/PREREG_*.md files.
"""
import json
from pathlib import Path

import numpy as np
from scipy import stats

ROOT = Path(__file__).resolve().parents[1]


def load_json(rel):
    p = ROOT / rel
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


SEARCH = load_json("runs/oakink_axis_search.json")
GRABDIAG = load_json("runs/axis_screen_grab_diagnostics.json")
OAK2DIAG = load_json("runs/axis_screen_oakink2_diagnostics.json")
SCREEN = load_json("runs/axis_screen.json")
OAK2SCREEN = load_json("runs/oakink2_axis_screen.json")


def find_row(blob, *keys):
    """Return the first dict in blob whose values match all key fragments."""
    if blob is None:
        return None
    rows = blob.get("rows", blob)
    items = rows.values() if isinstance(rows, dict) else rows
    if isinstance(rows, dict):
        for k, v in rows.items():
            if all(str(key).lower() in str(k).lower() for key in keys) and isinstance(v, dict):
                return v
    for r in items:
        if not isinstance(r, dict):
            continue
        hay = " ".join(str(r.get(f, "")) for f in ("pair", "axis", "name", "left", "right", "mode", "bundle")).lower()
        if all(str(key).lower() in hay for key in keys):
            return r
    return None


def rel_vals(dirs, budget=256):
    pen, relv = [], []
    for d in dirs:
        p = ROOT / "runs" / d / "results.json"
        if not p.exists():
            continue
        for r in json.loads(p.read_text(encoding="utf-8"))["results"]:
            if r["kind"] == "perframe" and r["budget"] == budget:
                pen.append(r["penalty"])
                relv.append(100 * r["penalty"] / r["naive"]["mse_target"])
    return np.array(pen), np.array(relv)


def pfmt(p):
    if not np.isfinite(p):
        return "--"
    if p < 1e-12:
        return "$<10^{-12}$"
    if p < 1e-4:
        return f"$<10^{{{int(np.ceil(np.log10(p)))}}}$"
    return f"{p:.2f}" if p >= 0.1 else f"{p:.3f}" if p >= 0.01 else f"{p:.4f}"


CONTROL_PEN, CONTROL_REL = rel_vals(["pc_easy_rerun"])

# label, sweep dirs, expected seeds, screen row (blob, key fragments)
ROWS = [
    ("OakInk-Image, category $\\times$ subject (no interaction)", ["oakink_category_subject"], 40,
     (SEARCH, ("category", "subject"))),
    ("GRAB, shape $\\times$ fine intent (stride 4)", ["grab_shape_s4"], 40, (GRABDIAG, ("grab",))),
    ("GRAB, shape $\\times$ fine intent, grasp only", ["grab_grasp_s32"], 40, (GRABDIAG, ("grasp",))),
    ("GRAB, shape $\\times$ fine intent, planted", ["grab_planted_s32"], 40, (GRABDIAG, ("planted",))),
    ("OakInk2, transitions (stride 4)", ["oakink2_transitions_s4"], 12, (OAK2SCREEN, ("transition",))),
    ("OakInk2, scene $\\times$ primitive, primitive segments", ["oakink2_primseg_s4"], 20, (OAK2DIAG, ("primseg",))),
    ("OakInk2, subject $\\times$ verb (held 3)", ["oakink2_subject_verb_h3_a", "oakink2_subject_verb_h3_b",
                                                  "oakink2_subject_verb_h3_c"], 40, (OAK2SCREEN, ("subject", "verb"))),
]

def main():
    # Only when run directly. Importing this module must never print a sweep's numbers: doing so once showed an
    # interim value of a pre-registered sweep that was meant to be read only at its full seed count.
    print("% Table II rows, generated by scripts/emit_table_rows.py")
    for label, dirs, expected, (blob, keys) in ROWS:
        pen, relv = rel_vals(dirs)
        if len(pen) == 0:
            print(f"% {label}: no rows yet")
            continue
        scr = find_row(blob, *keys)
        if scr is None:
            eta_l = eta_r = exc = z = None
        else:
            eta_l, eta_r = scr.get("left_only"), scr.get("right_only")
            exc, z = scr.get("excess"), scr.get("z")
            if exc is None and scr.get("interaction_r2") is not None:
                exc = scr.get("interaction_r2")
        p0 = stats.ttest_1samp(pen, 0).pvalue if len(pen) > 1 else float("nan")
        pc = stats.ttest_ind(relv, CONTROL_REL, equal_var=False).pvalue if len(relv) > 1 else float("nan")
        cells = [
            label,
            f"{eta_l:.3f}" if eta_l is not None else "--",
            f"{eta_r:.3f}" if eta_r is not None else "--",
            (f"{exc:+.4f} ({z:.1f})" if exc is not None and z is not None else "--"),
            f"{pen.mean():+.5f}",
            f"{relv.mean():+.1f}",
            pfmt(p0),
            pfmt(pc),
            str(len(pen)),
        ]
        mark = "" if len(pen) >= expected else f"  % PARTIAL {len(pen)}/{expected}"
        print(" & ".join(cells) + " \\\\" + mark)


if __name__ == "__main__":
    main()
