"""Supplement table: every sweep directory in runs/ that holds a results.json, with its settings and, where the
perframe prior was trained, its mean penalty. Written for docs/tmlr/PAPER_TMLR.md Appendix D, which lists the
real-data sweeps in the text and points here for the rest. Sweeps that are still running are listed with their
seed count and NO value, so that nothing is read before its declared seed count.

Output: docs/tmlr/supplement_all_sweeps.md
"""
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
RUNNING = set()  # the three sweeps that were running on 2026-09-29 finished at 40 seeds and were read
WHERE = {
    "pc_easy_rerun": "Table 1", "pc_hard_rerun": "Table 1", "grab_planted_s32": "Section 4.1",
    "grab_shape_v2": "Section 4.1, Appendix B", "sham_oakink_category": "Table 1", "sham_grab_shape": "Table 1",
    "sham_taco_action_tool": "Table 1", "oakink_official_category": "Table 2",
    "oakink_category_rest": "Table 2", "oakink_official_attr": "Table 2", "oakink_attr_more": "Table 2",
    "oakink_category_subject": "Table 2", "taco_action_tool": "Table 2, Section 4.4", "grab_shape_s4": "Table 2",
    "grab_shapeclass": "Table 2", "oakink2_scene_verb": "Table 2", "oakink2_scene_primitive": "Table 2, Appendix B",
    "pc_oakink_b64": "Table 3", "pc_oakink_pair_aligned": "Table 3",
    "pc_oakink_pair_misaligned": "Table 3", "pc_oakink_pair_aligned_wc": "Table 4",
    "pc_oakink_pair_misaligned_wc": "Table 4", "pc_oakink_dofdamage": "Appendix B", "pc_oakink_sparse": "Appendix B",
    "grab_grasp_s32": "Appendix B", "oakink2_scene_primitive_b64": "Appendix B", "oakink2_primseg_rep": "Appendix B",
    "oakink2_primseg_b896": "Appendix B",
    "oakink_class_rep": "Table 2 (replication)", "oakink2_transitions_rep": "Table 2 (replication)",
    "grab_shape_b64": "Section 4.2", "oakink_class_v1": "Table 2 caption (original)",
    "oakink2_transitions_s4": "Table 2 caption (original)",
}
lines = ["# Every sweep in runs/", "",
         "Generated by `scripts/list_all_sweeps.py`. Penalty is the mean over seeds of the perframe prior's penalty as a",
         "percentage of the naive error, at the first budget listed; `-` where the perframe prior was not trained or the",
         "sweep is still running. 'Where' names the place in the manuscript; sweeps without one are listed in Appendix D",
         "(real data) or are development runs and runs of a second architecture outside the paper's scope.", "",
         "| Sweep | Bundle | Grid | Budgets | Stride | Priors trained | Seeds | Penalty (%) | Where |",
         "|---|---|---|---|---|---|---|---|---|"]
for f in sorted((ROOT / "runs").glob("*/results.json")):
    d = f.parent.name
    J = json.loads(f.read_text(encoding="utf-8"))
    a, R = J.get("args", {}), [r for r in J.get("results", []) if isinstance(r, dict)]
    budgets = a.get("budgets") or []
    kinds = sorted({r.get("kind") for r in R if r.get("kind")})
    seeds = sorted({r.get("seed") for r in R if r.get("seed") is not None})
    val = "-"
    if d not in RUNNING and budgets:
        x = [100 * r["penalty"] / r["naive"]["mse_target"] for r in R
             if r.get("kind") == "perframe" and r.get("budget") == budgets[0] and "penalty" in r]
        if len(x) >= 2:
            val = f"{np.mean(x):+.2f}"
    status = "running" if d in RUNNING else WHERE.get(d, "")
    lines.append(f"| {d} | {Path(str(a.get('bundle', '-'))).name} | {a.get('granularity') or '-'} | "
                 f"{', '.join(map(str, budgets)) or '-'} | {a.get('stride', '-')} | {', '.join(kinds)} | {len(seeds)} | "
                 f"{val} | {status} |")
out = ROOT / "docs" / "tmlr" / "supplement_all_sweeps.md"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(out, len(lines) - 9, "sweeps")
